[env]
TERM = "xterm-256color"

[window]
opacity = 0.95

padding.x = 10
padding.y = 10

decorations = "None"
decorations_theme_variant = "Dark" #"Light"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 12.0

[mouse]
hide_when_typing = false

[general]
import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/tokyo-night-storm.toml"

]

# [colors.primary]
# background = '#000000'
# foreground = '#ffffff'
